receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  memory_limiter:
    check_interval: 1s
    limit_mib: 256
    spike_limit_mib: 64
  batch:
    timeout: 5s
    send_batch_size: 1024

exporters:
  opensearch:
    http:
      endpoint: "http://opensearch:9200"
    logs_index: "otel-logs-%{service.name}"
    logs_index_fallback: "unknown-service"
    logs_index_time_format: "yyyy.MM.dd"
    traces_index: "otel-traces-%{service.name}"
    traces_index_fallback: "unknown-service"
    traces_index_time_format: "yyyy.MM.dd"

service:
  pipelines:
    logs:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [opensearch]
    traces:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [opensearch]
