receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  memory_limiter:
    check_interval: 1s
    limit_mib: 256
    spike_limit_mib: 64
  batch:
    timeout: 5s
    send_batch_size: 1024

exporters:
  otlphttp/victoriametrics:
    compression: gzip
    metrics_endpoint: "http://victoriametrics:8428/opentelemetry/v1/metrics"
  otlphttp/victorialogs:
    compression: gzip
    logs_endpoint: "http://victorialogs:9428/insert/opentelemetry/v1/logs"
  otlphttp/victoriatraces:
    compression: gzip
    traces_endpoint: "http://victoriatraces:10428/insert/opentelemetry/v1/traces"

service:
  pipelines:
    logs:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [otlphttp/victorialogs]
    traces:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [otlphttp/victoriatraces]
    metrics:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [otlphttp/victoriametrics]
