include_guard(GLOBAL)

function(nestdaq_enable_clang_tidy description)
  option(NESTDAQ_ENABLE_CLANG_TIDY "${description}" OFF)
  if(NESTDAQ_ENABLE_CLANG_TIDY)
    find_program(CLANG_TIDY_EXE NAMES clang-tidy REQUIRED)
    set(CMAKE_CXX_CLANG_TIDY "${CLANG_TIDY_EXE}" PARENT_SCOPE)
    message(STATUS "clang-tidy enabled: ${CLANG_TIDY_EXE}")
  endif()
endfunction()

function(nestdaq_configure_install_rpath)
  set(CMAKE_SKIP_BUILD_RPATH FALSE PARENT_SCOPE)
  set(CMAKE_BUILD_WITH_INSTALL_RPATH FALSE PARENT_SCOPE)
  set(CMAKE_INSTALL_RPATH_USE_LINK_PATH TRUE PARENT_SCOPE)
  if(APPLE)
    set(CMAKE_INSTALL_RPATH "@loader_path/../${CMAKE_INSTALL_LIBDIR}" PARENT_SCOPE)
  elseif(UNIX)
    set(CMAKE_INSTALL_RPATH "$ORIGIN/../${CMAKE_INSTALL_LIBDIR}" PARENT_SCOPE)
  endif()
endfunction()
